<?php

/**
 * @file
 * Allows a feed node to populate fields on itself.
 */

/**
 * Implements hook_module_implements_alter().
 */
function feeds_selfnode_processor_module_implements_alter(&$implementations, $hook) {
  if ($hook !== 'node_insert') {
    return;
  }

  // Move feeds_selfnode_processor to the front so that it executes before
  // Feeds.
  $group = $implementations['feeds_selfnode_processor'];
  unset($implementations['feeds_selfnode_processor']);
  $implementations = array('feeds_selfnode_processor' => $group) + $implementations;
}

/**
 * Implements hook_node_insert().
 */
function feeds_selfnode_processor_node_insert($node) {
  // Bail early if possible.
  if (!isset($node->feeds)) {
    return;
  }
  if (!$importer_id = feeds_get_importer_id($node->type)) {
    return;
  }

  $importer = feeds_importer($importer_id);

  if (!$importer->processor instanceof FeedsSelfNodeProcessor) {
    return;
  }

  // Start import if requested.
  if ($importer->processor->config['import_on_create']) {
    unset($node->feeds['suppress_import']);
  }
}
