<?php

/**
 * @file
 * Test module for feeds_selfnode_processor.
 */

/**
 * Implements hook_menu().
 */
function feeds_selfnode_processor_test_menu() {
  $items = array();

  $items['_feeds_selfnode_processor_test/csv'] = array(
    'page callback' => 'feeds_selfnode_processor_test_csv',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Page callback for _feeds_selfnode_processor_test/csv.
 */
function feeds_selfnode_processor_test_csv() {
  // Add the header and 2 rss files.
  $feeds_path = drupal_get_path('module', 'feeds');
  $rss1 = $GLOBALS['base_url'] . '/' . $feeds_path . '/tests/feeds/developmentseed.rss2';
  $rss2 = $GLOBALS['base_url'] . '/' . $feeds_path . '/tests/feeds/feed_without_guid.rss2';
  print implode("\n", array('url', $rss1, $rss2));
  drupal_exit();
}
